#!/bin/bash
### BEGIN INIT INFO
# Description:  HyperPelicanDailyReport
# title           :hyperpelican
# description     :This script will helps you to create a html reports for your Linux virtual machines across different clouds.
# author	        :Richardson Lima
# email           :contatorichardsonlima@gmail.com
# date            :20150102
# version         :0.1    
# Provides:          scriptname
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

RETVAL=0
script="hyperpelican.sh"

function start () {
   if [ "`ps aux | grep $script | grep -v grep`" != "" ]; then
      echo "The HyperPelican $script is already running."
      exit 1
   else
      /bin/bash /home/hyperpelican/scripts/dailyreport/$script &
   fi
}

function stop () {
   kill `ps aux | grep $script | grep -v "grep" | awk '{print $2}'`
}

function status () {
   if [ "`ps aux | grep $script | grep -v "grep"`" != "" ]; then
      return="Hyper Pelican Started."
   else
      return="Hyper Pelican Stopped."
   fi
   echo $return
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                sleep 2
                start
                ;;
        status)
                status
                ;;
        *)
                echo "Uso: $0 {start|stop|restart|status}"
                RETVAL=1
esac

exit $RETVAL
